services:
  - type: web
    name: boeing-proxy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOEING_COOKIES
        sync: false   # se carga manualmente en el dashboard de Render
      - key: SECRET_TOKEN
        sync: false   # se carga manualmente en el dashboard de Render
